name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to vm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/test
            git pull
            npm install
            npm run build
            pm2 restart test